server:
  port: 8082

spring:
  application:
    name: API-GATEWAY-SERVICE
    datasource:
      url: jdbc:postgresql://localhost:5432/UsersDB
      username: postgres
      password: domelite
      driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    gateway:
      routes:
        - id: docenti-endpoints
          uri: http://localhost:8080  # Servizio docenti
          predicates:
            - Path=/docenti/**

        - id: discenti-endpoints
          uri: http://localhost:8080  # Servizio discenti
          predicates:
            - Path=/discenti/**


        - id: corsi-endpoints
          uri: http://localhost:8081 # Servizio corsi
          predicates:
            - Path=/corsi/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG