server:
  port: 8082

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: docenti-endpoints
          uri: http://localhost:8080
          predicates:
            - Path=/admin/docenti/**
          filters:
            - StripPrefix=1

        - id: discenti-endpoints
          uri: http://localhost:8080
          predicates:
            - Path=/admin/discenti/**
          filters:
            - StripPrefix=1

        - id: corsi-endpoints
          uri: http://localhost:8081
          predicates:
            - Path=/admin/corsi/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.security: DEBUG